name: 'Enhancement Request'
description: 'Request new work.'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: 'Write a summary of the request. List acceptance criteria, explain how you reached this solution, and if there are alternatives.'
  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Summary'
  - type: markdown
    attributes:
      value: 'List all links helpful for others to understand your request.'
  - type: textarea
    attributes:
      label: 'Links'
